# Generated by configure.standalone
# Wed Oct 22 22:22:42 -03 2025

# Installation directories
PREFIX = /tmp/hfsutils-test
SBINDIR = /tmp/hfsutils-test/sbin

# Build tools
CC = gcc
CFLAGS = -g -O2 -DDEBUG -g3 -O0

# Build options
ENABLE_DEBUG = yes
ENABLE_STATIC = no
